module shapes_demo_typesupport
{
    module msg
    {
        struct KeylessShapeType {
            string color;
            long x;
            long y;
            long shapesize;
        };
    };
};
