module shapes_demo_typesupport
{
    module idl
    {
        @final
        struct KeylessShapeType {
            string color;
            long x;
            long y;
            long shapesize;
        };
    };
};
